start_program:
  description: Selects a program and starts it.
  fields:
    entity_id:
      description: Id of an entity associated with the home appliance.
      example: "switch.dishwasher_power"
    program:
      description: Program to select
      example: "Dishcare.Dishwasher.Program.Auto2"
    key:
      description: Key of the option.
      example: "BSH.Common.Option.StartInRelative"
    value:
      description: Value of the option.
      example: 1800
    unit:
      description: Unit for the option.
      example: "seconds"
select_program:
  description: Selects a program without starting it.
  fields:
    entity_id:
      description: Id of an entity associated with the home appliance.
      example: "switch.dishwasher_power"
    program:
      description: Program to select.
      example: "Dishcare.Dishwasher.Program.Auto2"
    key:
      description: Key of the option.
      example: "BSH.Common.Option.StartInRelative"
    value:
      description: Value of the option.
      example: 1800
    unit:
      description: Unit for the option.
      example: "seconds"
pause_program:
  description: Pauses the current running program.
  fields:
    entity_id:
      description: Id of an entity associated with the home appliance.
      example: "switch.dryer_power"
resume_program:
  description: Resumes a paused program.
  fields:
    entity_id:
      description: Id of an entity associated with the home appliance.
      example: "switch.dryer_power"
set_option_active:
  description: Sets an option for the active program.
  fields:
    entity_id:
      description: Id of an entity associated with the home appliance.
      example: "switch.dryer_power"
    key:
      description: Key of the option.
      example: "LaundryCare.Dryer.Option.DryingTarget"
    value:
      description: Value of the option.
      example: "LaundryCare.Dryer.EnumType.DryingTarget.IronDry"
set_option_selected:
  description: Sets an option for the selected program.
  fields:
    entity_id:
      description: Id of an entity associated with the home appliance.
      example: "switch.dryer_power"
    key:
      description: Key of the option.
      example: "LaundryCare.Dryer.Option.DryingTarget"
    value:
      description: Value of the option.
      example: "LaundryCare.Dryer.EnumType.DryingTarget.IronDry"
change_setting:
  description: Changes a setting.
  fields:
    entity_id:
      description: Id of an entity associated with the home appliance.
      example: "switch.dryer_power"
    key:
      description: Key of the setting.
      example: "BSH.Common.Setting.ChildLock"
    value:
      description: Value of the setting.
      example: "true"
